import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Auth pages",
    // description: "Generated by create next app",
  };

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <>
          <h1>This is auth layout</h1>
          {children}
      </>
    );
  }
  